#incident_info:
#  incident_size: 30 # 사고 규모 (총 환자 수)
#  latitude: 36.33229415139486 # 위도
#  longitude: 127.4346445159045 # 경도
#  incident_type: null # 사고 타입 설정 가능하게 추후 확장

entity_info:
  departure_time: "202601071632" # API 조회 시각 (YYYYMMDDHHMM)
  patient:
    incident_size: 30 # 사고 규모 (총 환자 수)
    latitude: 36.33229415139486 # 위도
    longitude: 127.4346445159045 # 경도
    incident_type: null # 사고 타입 설정 가능하게 추후 확장
    info_path: "./scenarios/exp_202601071633_dep_202601071632/(36.33229415139486,127.4346445159045)/patient_info.csv"
  hospital:
    load_data: True
    info_path: "./scenarios/exp_202601071633_dep_202601071632/(36.33229415139486,127.4346445159045)/hospital_info_road.csv"
    dist_Hos2Hos_euc_info: "./scenarios/exp_202601071633_dep_202601071632/(36.33229415139486,127.4346445159045)/distance_Hos2Hos_euc.csv"
    dist_Hos2Hos_road_info: "./scenarios/exp_202601071633_dep_202601071632/(36.33229415139486,127.4346445159045)/distance_Hos2Hos_road.csv"
    dist_Hos2Site_euc_info: "./scenarios/exp_202601071633_dep_202601071632/(36.33229415139486,127.4346445159045)/distance_Hos2Site_euc.csv"
    dist_Hos2Site_road_info: "./scenarios/exp_202601071633_dep_202601071632/(36.33229415139486,127.4346445159045)/distance_Hos2Site_road.csv"
    max_send_coeff: [1.0, 1.0]
  ambulance:
    load_data: True
    dispatch_distance_info: "./scenarios/exp_202601071633_dep_202601071632/(36.33229415139486,127.4346445159045)/amb_info_road.csv"
    velocity: 40 # unit: km/h
    handover_time: 0.0 # unit: minutes
    is_use_time: True # True: API duration 사용, False: 거리/속도 기반 계산
    duration_coeff: 1.0 # API duration 시간가중치 (기본값: 1.0, 환경적 요인 반영시 조정)
  uav:
    load_data: True
    dispatch_distance_info: "./scenarios/exp_202601071633_dep_202601071632/(36.33229415139486,127.4346445159045)/uav_info.csv"
    velocity: 80 # unit: km/h
    handover_time: 0.0 # unit: minutes
    is_use_time: False # UAV는 항상 유클리드 거리 기반

event_info_path: "event_info.json"

rule_info:
  isFullFactorial: True
  priority_rule: ["START", "ReSTART"]
  hos_select_rule: ["RedOnly", "YellowHalf"]
  red_mode_rule: ["OnlyUAV", "Both_UAVFirst", "Both_AMBFirst", "OnlyAMB"]
  yellow_mode_rule: ["OnlyUAV", "Both_UAVFirst", "Both_AMBFirst", "OnlyAMB"]

run_setting:
  totalSamples: 30 # number of samples
  random_seed: 0 # null, if do not want to fix
  rule_test: True
  eval_mode: True
  output_path: "./results/exp_202601071633_dep_202601071632"
  exp_indicator: "(36.33229415139486,127.4346445159045)"
  save_info: True # NotImplemented
